export const cvData = {
  name: "Cem Bilen",
  title: "Software Engineer",
  subtitle: "Full-stack · AI-native",
  contact: {
    email: "CXBilen@gmail.com",
    phone: "+90 530 040 23 92",
    location: "Izmir, Türkiye",
  },
  socials: [
    { label: "LinkedIn", href: "https://linkedin.com/in/cxbilen" },
    { label: "Portfolio", href: "https://cxbilen.com" },
    { label: "GitHub", href: "https://github.com/CXBilen" },
  ],
  skills: [
    "Frontend Development",
    "Backend Development",
    "API Integration",
    "Data Modeling",
    "AI-assisted Development",
    "AI API Integration",
    "Realtime Applications",
    "Test Automation",
    "UX / UI Design",
    "Design Systems",
    "CRO / A/B Testing",
    "Product Thinking",
  ],
  tools: [
    "TypeScript / JavaScript",
    "React",
    "Next.js",
    "Node.js",
    "Bun / Electron",
    "PostgreSQL / SQL",
    "Redis",
    "Supabase",
    "WebRTC / WebSocket / Socket.IO",
    "Google Gemini API",
    "Tailwind CSS",
    "Git / GitHub",
    "Playwright / Vitest",
    "Codex / Claude Code",
    "Figma",
    "GA4 / Funnels",
  ],
  about:
    "Software engineer with a foundation in computer programming and databases. I build full-stack web products, desktop tools and realtime applications, including AI integrations. My AI-native workflow combines Codex and Claude Code with architecture, typed contracts, code review and automated testing. UX, design systems and conversion optimization inform my engineering decisions.",
  experience: [
    {
      role: "Senior UX Engineer",
      company: "Efsora Labs",
      period: "Feb 2026 – Jul 2026 · Türkiye",
      body: "Led UX engineering and design systems across SaaS and web flows. Translated product requirements into user journeys, prototypes and implementation specifications, and standardized a design system of 40+ components.",
    },
    {
      role: "Senior CRO Executive",
      company: "Digital House",
      period: "Mar 2025 – Jan 2026 · Istanbul",
      body: "Owned CRO and UX for web and e-commerce, turning funnel analysis into prioritized A/B tests that lifted conversion +12% and reduced checkout drop-off −16%.",
    },
    {
      role: "UX/UI Designer",
      company: "Eva",
      period: "Sep 2023 – Aug 2024 · Izmir",
      body: "Designed end-to-end SaaS interfaces and Figma prototypes, simplifying complex flows into clear workflows and improving task-success in usability tests by +20%.",
    },
    {
      role: "Designer Project Manager",
      company: "innoscripta AG",
      period: "May 2023 – Jul 2023 · Berlin",
      body: "",
    },
    {
      role: "UX/UI Designer",
      company: "StudioMoco",
      period: "Dec 2022 – May 2023 · Nuremberg",
      body: "",
    },
    {
      role: "CRO Executive",
      company: "Hype",
      period: "Apr 2022 – Sep 2022 · Istanbul",
      body: "",
    },
    {
      role: "Web Developer",
      company: "İnce Fikirler",
      period: "Mar 2019 – Feb 2020 · Izmir",
      body: "",
    },
  ],
  education: [
    {
      title: "Associate's, Computer Programming",
      org: "Izmir University of Economics",
      period: "2014 – 2016",
      body: "Software development, web programming and database fundamentals.",
    },
    {
      title: "Database Interactive Programming",
      org: "Ç. Altan Anatolian Technical HS",
      period: "2010 – 2014",
      body: "",
    },
  ],
  selectedWork: [
    {
      name: "Surfel",
      desc: "SaaS in development: Next.js/TypeScript monorepo, PostgreSQL data models, role-based access, APIs, webhooks and background jobs.",
    },
    {
      name: "cxbilen.com",
      desc: "Live Next.js/TypeScript portfolio with reusable UI components, shared-source PDF/DOCX CV exports, component tests and browser checks.",
    },
    {
      name: "Dev Migration Assistant",
      desc: "Released Electron/React desktop tool for Git working state and AI context migration; typed IPC, encrypted archives and checksum-verified restore.",
    },
    {
      name: "PlayAgain",
      desc: "Browser gaming application with Next.js, WebRTC, WebSocket and Redis; phone controllers, QR room pairing and save-state APIs.",
    },
    {
      name: "Looplift",
      desc: "Next.js/Supabase beta for AI-assisted conversion audits; versioned experiment patches, human approval, measurement guardrails and rollback.",
    },
    {
      name: "Maestro",
      desc: "AI execution workspace with Next.js, Bun workers, PostgreSQL and Redis; typed job lifecycle, streamed output and artifact review.",
    },
    {
      name: "SkyWise",
      desc: "Next.js/React travel-assistant case study with typed interaction flows, rule-based intents and simulated service integrations.",
    },
    {
      name: "LENZ",
      desc: "Live virtual try-on product using Next.js, Supabase and Gemini image-generation APIs; merchant authentication, rate limits and usage tracking.",
    },
    {
      name: "ZEDrift",
      desc: "Browser driving game with React/Three.js rendering, drift physics, Socket.IO multiplayer and PostgreSQL/Prisma account persistence.",
    },
  ],
};
