export const cvData = {
  name: "Cem Bilen",
  title: "Software Engineer",
  subtitle: "Full-stack · AI-native",
  contact: {
    email: "CXBilen@gmail.com",
    phone: "+90 530 040 23 92",
    location: "Izmir, Türkiye",
  },
  socials: [
    { label: "LinkedIn", href: "https://linkedin.com/in/cxbilen" },
    { label: "Portfolio", href: "https://cxbilen.com" },
    { label: "GitHub", href: "https://github.com/CXBilen" },
  ],
  skills: [
    "Frontend Development",
    "Backend Development",
    "API Integration",
    "Data Modeling",
    "AI-assisted Development",
    "Test Automation",
    "UX / UI Design",
    "Design Systems",
    "CRO / A/B Testing",
    "Product Thinking",
  ],
  tools: [
    "TypeScript / JavaScript",
    "React",
    "Next.js",
    "Node.js",
    "PostgreSQL / SQL",
    "Supabase",
    "Tailwind CSS",
    "Git / GitHub",
    "Playwright / Vitest",
    "Codex / Claude Code",
    "Figma",
    "GA4 / Funnels",
  ],
  about:
    "Software engineer with a foundation in computer programming and databases. I build web products across frontend, backend and API integrations, using AI throughout development alongside architecture, code review and testing. My experience in UX, design systems and conversion optimization connects technical decisions to user needs and business goals.",
  experience: [
    {
      role: "Senior UX Engineer",
      company: "Efsora Labs",
      period: "Feb 2026 – Jul 2026 · Türkiye",
      body: "Led UX engineering and design systems across SaaS and web flows. Translated product requirements into user journeys, prototypes and implementation specifications, and standardized a design system of 40+ components.",
    },
    {
      role: "Senior CRO Executive",
      company: "Digital House",
      period: "Mar 2025 – Jan 2026 · Istanbul",
      body: "Owned CRO and UX for web and e-commerce, turning funnel analysis into prioritized A/B tests that lifted conversion +12% and reduced checkout drop-off −16%.",
    },
    {
      role: "UX/UI Designer",
      company: "Eva",
      period: "Sep 2023 – Aug 2024 · Izmir",
      body: "Designed end-to-end SaaS interfaces and Figma prototypes, simplifying complex flows into clear workflows and improving task-success in usability tests by +20%.",
    },
    {
      role: "Designer Project Manager",
      company: "innoscripta AG",
      period: "May 2023 – Jul 2023 · Berlin",
      body: "",
    },
    {
      role: "UX/UI Designer",
      company: "StudioMoco",
      period: "Dec 2022 – May 2023 · Nuremberg",
      body: "",
    },
    {
      role: "CRO Executive",
      company: "Hype",
      period: "Apr 2022 – Sep 2022 · Istanbul",
      body: "",
    },
    {
      role: "Web Developer",
      company: "İnce Fikirler",
      period: "Mar 2019 – Feb 2020 · Izmir",
      body: "",
    },
  ],
  education: [
    {
      title: "Associate's, Computer Programming",
      org: "Izmir University of Economics",
      period: "2014 – 2016",
      body: "Software development, web programming and database fundamentals.",
    },
    {
      title: "Database Interactive Programming",
      org: "Ç. Altan Anatolian Technical HS",
      period: "2010 – 2014",
      body: "",
    },
  ],
  selectedWork: [
    {
      name: "Surfel",
      desc: "SaaS product in development: full-stack application, APIs and data access, built with AI-assisted workflows.",
    },
    {
      name: "cxbilen.com",
      desc: "Next.js portfolio with shared theme tokens, responsive components, CV downloads and automated tests.",
    },
    {
      name: "SkyWise",
      desc: "Travel-assistant case study: typed React interfaces and interaction flows with simulated service integrations.",
    },
  ],
};
