import { mkdir, writeFile, copyFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";
import { chromium } from "playwright";
import { cvData } from "../lib/cv.ts";

// Node.js 22.18+. Run `npx playwright install chromium` first, or set
// CV_CHROMIUM_PATH to an existing Chrome/Chromium executable.
// Copy source: lib/cv.ts. Design: COSS default Inter/neutral preset.
// https://coss.com/ui/docs/get-started  https://coss.com/ui/docs/styling
const root = fileURLToPath(new URL("..", import.meta.url));
const sourceDir = path.join(root, "Cem Bilen CV 2026 HTML");
const outputDir = path.join(root, "public/cv");
const htmlPath = path.join(sourceDir, "Cem Bilen CV.dc.html");
const normalize = (value) => value.replace(/[\u2013\u2014\u2212]/g, "-");
const escape = (value) => normalize(String(value))
  .replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const social = Object.fromEntries(cvData.socials.map((item) => [item.label, item.href]));
const link = (label, href) => `<a href="${escape(href)}">${escape(label)}</a>`;
const entries = (items, education = false) => items.map((item) => `<article class="entry">
  <h3>${escape(education ? item.title : item.role)} | ${escape(education ? item.org : item.company)} <span class="period">| ${escape(item.period)}</span></h3>
  ${item.body ? `<p>${escape(item.body)}</p>` : ""}
</article>`).join("\n");

const html = `<!DOCTYPE html>
<!-- Generated by scripts/export-cv.mjs from lib/cv.ts. -->
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(cvData.name)} CV 2026 - ${escape(cvData.title)}</title>
<meta name="description" content="${escape(cvData.about)}">
<style>
  @font-face { font-family: Inter; font-style: normal; font-weight: 400; font-display: block; src: url('./fonts/Inter-Regular.ttf') format('truetype'); }
  @font-face { font-family: Inter; font-style: normal; font-weight: 700; font-display: block; src: url('./fonts/Inter-Bold.ttf') format('truetype'); }
  :root { --background: #fff; --foreground: #262626; --muted-foreground: #686868; --border: #ebebeb; }
  :root[data-theme="dark"] { --background: #161616; --foreground: #f5f5f5; --muted-foreground: #818181; --border: #242424; }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body { font: 400 10.5pt/1.24 Inter, Arial, sans-serif; color: var(--foreground); background: var(--background); font-variant-ligatures: none; font-feature-settings: "calt" 0, "liga" 0; }
  .cv { max-width: 210mm; margin: 0 auto; padding: 12mm; }
  h1 { font-size: 25pt; line-height: 1.1; margin: 0 0 3pt; font-weight: 700; letter-spacing: -.035em; }
  .role { font-size: 11.5pt; margin: 0 0 6pt; }
  .contact { font-style: normal; }
  .contact p { margin: 0; }
  a { color: inherit; text-decoration: none; }
  h2 { font-size: 11.5pt; line-height: 1.2; font-weight: 700; margin: 9pt 0 4pt; padding: 0; }
  h3 { font-size: 10.5pt; line-height: 1.24; font-weight: 700; margin: 0; }
  p { margin: 0; }
  .period { color: var(--muted-foreground); font-weight: 400; }
  .entry { margin-top: 5pt; break-inside: avoid; }
  .entry:first-of-type { margin-top: 0; }
  .entry p + p { margin-top: 2pt; }
  .skills p + p { margin-top: 3pt; }
  .projects p + p { margin-top: 4pt; }
  h2, h3 { break-after: avoid; }
  p { orphans: 2; widows: 2; }
  .theme-toggle { position: fixed; top: 16px; right: 16px; border: 1px solid var(--border); padding: 9px 12px; border-radius: .625rem; background: var(--background); color: var(--foreground); font: 400 12px/1 Inter,sans-serif; cursor: pointer; }
  @page { size: A4; margin: 12mm; background: var(--background); }
  @media print { html { -webkit-print-color-adjust: exact; print-color-adjust: exact; } .cv { width: auto; max-width: none; margin: 0; padding: 0; } .theme-toggle { display: none; } }
  @media screen and (max-width: 700px) { .cv { padding: 28px 20px; } .theme-toggle { position: static; margin: 0 20px 20px; } }
</style>
</head>
<body>
<main class="cv">
  <h1>${escape(cvData.name)}</h1>
  <p class="role">${escape(cvData.title)} | ${escape(cvData.subtitle)}</p>
  <div class="contact">
    <p>${link(cvData.contact.email, `mailto:${cvData.contact.email}`)} | ${link(cvData.contact.phone, `tel:${cvData.contact.phone.replaceAll(" ", "")}`)} | ${escape(cvData.contact.location)}</p>
    <p>Portfolio: ${link(social.Portfolio, social.Portfolio)} | GitHub: ${link(social.GitHub, social.GitHub)}</p>
    <p>LinkedIn: ${link(social.LinkedIn, social.LinkedIn)}</p>
  </div>
  <section>
    <h2>Summary</h2>
    <p>${escape(cvData.about)}</p>
  </section>
  <section class="skills">
    <h2>Technical Skills</h2>
    <p><strong>Technologies:</strong> ${cvData.tools.map(escape).join(", ")}.</p>
    <p><strong>Capabilities:</strong> ${cvData.skills.map(escape).join(", ")}.</p>
  </section>
  <section class="projects">
    <h2>Projects</h2>
    ${cvData.selectedWork.map((item) => `<p><strong>${escape(item.name)}:</strong> ${escape(item.desc)}</p>`).join("\n    ")}
  </section>
  <section>
    <h2>Experience</h2>
    ${entries(cvData.experience)}
  </section>
  <section>
    <h2>Education</h2>
    ${entries(cvData.education, true)}
  </section>
</main>
<button class="theme-toggle" type="button" aria-label="Switch color theme">Switch theme</button>
<script>
  const requestedTheme = new URLSearchParams(location.search).get('theme');
  if (requestedTheme === 'dark') document.documentElement.dataset.theme = 'dark';
  document.querySelector('.theme-toggle').addEventListener('click', () => {
    document.documentElement.dataset.theme = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark';
  });
</script>
</body>
</html>
`;

const plainText = [
  cvData.name,
  `${cvData.title} | ${cvData.subtitle}`,
  `${cvData.contact.email} | ${cvData.contact.phone} | ${cvData.contact.location}`,
  `Portfolio: ${social.Portfolio} | GitHub: ${social.GitHub}`,
  `LinkedIn: ${social.LinkedIn}`,
  "", "Summary", cvData.about,
  "", "Technical Skills", `Technologies: ${cvData.tools.join(", ")}.`, `Capabilities: ${cvData.skills.join(", ")}.`,
  "", "Projects", ...cvData.selectedWork.map((item) => `${item.name}: ${item.desc}`),
  "", "Experience", ...cvData.experience.flatMap((item) => [`${item.role} | ${item.company}`, item.period, ...(item.body ? [item.body] : []), ""]),
  "Education", ...cvData.education.flatMap((item) => [`${item.title} | ${item.org}`, item.period, ...(item.body ? [item.body] : []), ""]),
].map(normalize).join("\n");

await mkdir(outputDir, { recursive: true });
await mkdir(path.join(sourceDir, "PDF"), { recursive: true });
await writeFile(htmlPath, html.replace(/^[\t ]+$/gm, ""));
await writeFile(path.join(outputDir, "Cem Bilen CV 2026.txt"), `${plainText.trim()}\n`);
// Optional input to scripts/export-cv-docx.py. Avoids independent CV copy.
if (process.env.CV_DATA_JSON) await writeFile(process.env.CV_DATA_JSON, JSON.stringify(cvData));
const browser = await chromium.launch({ executablePath: process.env.CV_CHROMIUM_PATH });
try {
  const page = await browser.newPage({ viewport: { width: 900, height: 1200 } });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(pathToFileURL(htmlPath).href, { waitUntil: "networkidle" });
  await page.evaluate(() => document.fonts.ready);
  const checks = await page.evaluate(() => ({
    fontsReady: document.fonts.check('400 14px Inter') && document.fonts.check('700 14px Inter'),
    fontCount: document.fonts.size,
    horizontalOverflow: document.documentElement.scrollWidth > innerWidth,
  }));
  if (errors.length || !checks.fontsReady || checks.fontCount !== 2 || checks.horizontalOverflow) {
    throw new Error(`CV render validation failed: ${JSON.stringify({ errors, ...checks })}`);
  }
  for (const theme of ["light", "dark"]) {
    await page.evaluate((theme) => { document.documentElement.dataset.theme = theme; }, theme);
    const filename = `Cem Bilen CV 2026 ${theme === "dark" ? "Dark" : "Light"}.pdf`;
    const pdfPath = path.join(sourceDir, "PDF", filename);
    await page.pdf({ path: pdfPath, format: "A4", printBackground: true, preferCSSPageSize: true, tagged: true });
    await copyFile(pdfPath, path.join(outputDir, filename));
    if (theme === "light") {
      await copyFile(pdfPath, path.join(outputDir, "Cem Bilen CV 2026.pdf"));
      await copyFile(pdfPath, path.join(sourceDir, "PDF/Cem Bilen CV 2026.pdf"));
    }
    console.log(`Exported ${filename}`);
  }
} finally {
  await browser.close();
}
